name: Check Plugins Installed

on:
  pull_request:

jobs:
  buildx:
    runs-on: ubuntu-22.04
    env:
      TERM: xterm
    strategy:
      fail-fast: false
      matrix:
        plugins:
          # - acquia
          # - apache
          # - backdrop
          # - compose
          - core
          - core-next
          # - dotnet
          # - drupal
          # - elasticsearch
          # - go
          # - joomla
          # - lagoon
          # - lamp
          # - laravel
          # - lemp
          # - mailhog
          # - mariadb
          # - mean
          # - memcached
          # - mongo
          # - mssql
          # - mysql
          # - nginx
          # - node
          # - pantheon
          # - php
          # - phpmyadmin
          # - platformsh
          # - postgres
          # - python
          # - redis
          # - ruby
          # - solr
          # - symfony
          # - tomcat
          # - wordpress
          # - varnish

    steps:
      # Install deps and cache
      # Eventually it would be great if these steps could live in a separate YAML file
      # that could be included in line to avoid code duplication
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install Yarn dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      # package cli so we can use that in setup lando
      - name: Package CLI
        run: yarn cli:build
      - name: Setup locally built lando
        uses: lando/setup-lando@v2
        with:
          lando-version: ./dist/@lando/cli
          telemetry: false

      # Checks to make sure the plugins listed in the matrix have the right path
      - name: Check if @lando/${{ matrix.plugins }} is installed correctly
        run: |
          lando config --path plugins | grep node_modules/@lando/${{ matrix.plugins }}
